language: node_js
sudo: false
node_js:
- '0.10'
- '0.12'
before_script:
- gulp lint
script:
- gulp test
- gulp karma
- gulp smoke
deploy:
  provider: npm
  on:
    tags: true
    repo: stackOverMind/mockwilddog
    all_branches: true
